### ISSUE TITLE
Getting started for Arduino uno r3 still uses Arduino IDE 1.x.x

### ISSUE THREAD

**Issue by V205Arduino** [arduino/docs-content#1156]
Getting started for Arduino uno r3 still uses Arduino IDE 1.x.x
Should this be changed to use Arduino 2.x.x since this is the newest release?

**Comment by karlsoderby** [comment]
Hi @V205Arduino . Thanks for reporting this, and it is indeed true for a number of legacy boards that were released prior to the release of IDE 2. 

We are working on a general solution for this type of documentation, but for now I can't tell you when that will be released!

**Comment by V205Arduino** [comment]
Ok thanks!  Anything I can contribute to?

**Comment by karlsoderby** [comment]
Hi again @V205Arduino and sorry for the late reply. We have updated the docs, so that you are now linked to a generic installation guide for **any** Arduino core.
- This guide shows at the top how to install a core (very nicely via the built-in board manager in the IDE 2)
- It has a specific section (in this case, it is AVR) for every core, and which board is linked to it.

Thank you! I am closing this issue but feel free to open it again in case there's still some open issues. Have a great day!

**Comment by V205Arduino** [comment]
Ok thanks!
