### ISSUE TITLE
 built-in LED pin number for the Nano 33 IoT is missing in the Data sheet 

### ISSUE THREAD

**Issue by Lenardgeorge** [arduino/docs-content#200]
The built-in LED pin for the Nano 33 IoT board Is D13. It would be nice to mention this in the table where we describe all the pins  and their functions. So far D13 is only described as a GPIO pin.

**Comment by lunnea** [comment]
Ill check it out guys :)

**Comment by jhansson-ard** [comment]
PR available here: https://github.com/arduino/docs-content/pull/208

**Comment by per1234** [comment]
@jhansson-ard https://github.com/arduino/docs-content/pull/208 is for the Nano 33 BLE, while this issue is about the Nano 33 IoT, so the equivalent change would need to be made at https://github.com/arduino/docs-content/blob/main/content/hardware/03.nano/boards/nano-33-iot/datasheet/datasheet.md#headers to resolve

**Comment by jhansson-ard** [comment]
PR is merged and the live page will be updated shortly!
