### ISSUE TITLE
Does.arduino.cc is unaccessable

### ISSUE THREAD

**Issue by DIYables** [arduino/docs-content#2235]
I tried to access Arduino docs, but the page is unaccessible and shown as below
![Image](https://github.com/user-attachments/assets/7bfddba7-d609-4b1e-a3e7-d3f469c3051f)

I guess this is mis-configured error on Amazon S3

**Comment by Serjlee** [comment]
Thanks @DIYables, I think we missed a redirect when the libraries section was overhauled

Until it's fixed, you can find the documentation for `SD.open()` at the bottom of this page: https://docs.oniudra.cc/libraries/sd/

**Comment by Serjlee** [comment]
The redirect was fixed: it will likely be cached by most browsers since it was marked as permanent, but will _eventually_ update for everyone

Old per-function URLs such as https://www.oniudra.cc/reference/en/libraries/sd/begin will now redirect to the new library page (ie: https://docs.oniudra.cc/libraries/sd) containing docs for all library functions
