### ISSUE TITLE
Copy v1 Linux usermod installation step to v2

### ISSUE THREAD

**Issue by kuhrusty** [arduino/docs-content#301]
https://docs.arduino.cc/software/ide-v1/tutorials/Linux has a "Please Read" section which talks about running `usermod` to give  the user permission to write to the serial port.  I don't see this in the v2 instructions, but it's still necessary there too; it should be copied to ide-v2-downloading-and-installing.md or (probably better) ide-v2-uploading-a-sketch.md.

**Comment by per1234** [comment]
@karlsoderby that does not resolve this request. Even when using the AppImage version of Arduino IDE 2.x, it is still necessary to give the user permissions to access the serial port in order to avoid the dreaded 'can't open device "/dev/ttyACM0": Permission denied' error.

Note that this is a different process from giving the AppImage file executable permissions.

**Comment by karlsoderby** [comment]
My bad @per1234 , I have opened a PR to add the instructions that were present in the older tutorial (#436)
